broker:
  db_path: tasks.db
  metrics_port: 9000
worker:
  broker_url: http://broker:8000
  metrics_port: 9001
  concurrency: 2
node:
  host: localhost
  port: 50051
security:
  api_key: null
  api_tokens: null
  api_key_env: API_KEY
  api_tokens_env: API_TOKENS
  plugin_signing_key: null
  plugin_signing_key_env: PLUGIN_SIGNING_KEY
  worker_token: null
  worker_token_env: WORKER_TOKEN
sandbox:
  root: sandbox
  allowed_commands:
    - echo
    - touch
planner:
  budget: 0
  warning_threshold: 0.8

logging:
  config_file: logging.conf
  level: INFO
  logfile: null

reward:
  correctness: 1.0
  performance: 0.5
  style: 0.2
  complexity: 0.2
