version: '3'
services:
  orchestrator:
    build:
      context: .
      dockerfile: orchestrator/Dockerfile
    volumes:
      - ./tasks.yml:/app/tasks.yml
      - ./state.json:/app/state.json
      - ./config.yaml:/app/config.yaml
    environment:
      BROKER_URL: http://broker:8000
      WORKER_METRICS_PORT: "9001"
      BROKER_METRICS_PORT: "9000"
    depends_on:
      - broker
      - worker
      - io-service
  broker:
    build:
      context: .
      dockerfile: broker/Dockerfile
    environment:
      DB_PATH: /data/tasks.db
      BROKER_METRICS_PORT: "9000"
    volumes:
      - broker-data:/data
    ports:
      - "8000:8000"
      - "9000:9000"
  worker:
    build:
      context: .
      dockerfile: worker/Dockerfile
    environment:
      BROKER_URL: http://broker:8000
      WORKER_METRICS_PORT: "9001"
    depends_on:
      - broker
    ports:
      - "9001:9001"
  io-service:
    build:
      context: .
      dockerfile: services/node/Dockerfile
    environment:
      PORT: "50051"
      METRICS_PORT: "9100"
    ports:
      - "50051:50051"
      - "9100:9100"

volumes:
  broker-data:
