version: '3'
services:
  broker:
    build:
      context: .
      dockerfile: broker/Dockerfile
    ports:
      - "8000:8000"
  worker:
    build:
      context: .
      dockerfile: worker/Dockerfile
  io-service:
    build:
      context: .
      dockerfile: services/node/Dockerfile
    ports:
      - "50051:50051"
      - "9100:9100"
