global:
  scrape_interval: 15s
scrape_configs:
  - job_name: 'otel-collector'
    scheme: https
    tls_config:
      ca_file: /certs/ca.crt
      insecure_skip_verify: true
    static_configs:
      - targets: ['otel-collector:8889']
  - job_name: 'ai-swa-services'
    metrics_path: /metrics
    static_configs:
      - targets:
          - 'broker:9000'
          - 'worker:9001'
          - 'orchestrator:8000'
          - 'io-service:9100'
