# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: bridge.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'bridge.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x62ridge.proto\x12\x05\x61iswa\"\x1e\n\x0eReverseRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\"\x1c\n\x0cReverseReply\x12\x0c\n\x04text\x18\x01 \x01(\t2A\n\x06\x42ridge\x12\x37\n\x07Reverse\x12\x15.aiswa.ReverseRequest\x1a\x13.aiswa.ReverseReply\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'bridge_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_REVERSEREQUEST']._serialized_start=23
  _globals['_REVERSEREQUEST']._serialized_end=53
  _globals['_REVERSEREPLY']._serialized_start=55
  _globals['_REVERSEREPLY']._serialized_end=83
  _globals['_BRIDGE']._serialized_start=85
  _globals['_BRIDGE']._serialized_end=150
# @@protoc_insertion_point(module_scope)
