# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: plugin_marketplace.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18plugin_marketplace.proto\x12\x05\x61iswa\"\x07\n\x05\x45mpty\"\x1b\n\rPluginRequest\x12\n\n\x02id\x18\x01 \x01(\t\"7\n\nPluginInfo\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0f\n\x07version\x18\x03 \x01(\t\"0\n\nPluginList\x12\"\n\x07plugins\x18\x01 \x03(\x0b\x32\x11.aiswa.PluginInfo\"\x1a\n\nPluginData\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\x32\x82\x01\n\x11PluginMarketplace\x12\x30\n\x0bListPlugins\x12\x0c.aiswa.Empty\x1a\x11.aiswa.PluginList\"\x00\x12;\n\x0e\x44ownloadPlugin\x12\x14.aiswa.PluginRequest\x1a\x11.aiswa.PluginData\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'plugin_marketplace_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_EMPTY']._serialized_start=35
  _globals['_EMPTY']._serialized_end=42
  _globals['_PLUGINREQUEST']._serialized_start=44
  _globals['_PLUGINREQUEST']._serialized_end=71
  _globals['_PLUGININFO']._serialized_start=73
  _globals['_PLUGININFO']._serialized_end=128
  _globals['_PLUGINLIST']._serialized_start=130
  _globals['_PLUGINLIST']._serialized_end=178
  _globals['_PLUGINDATA']._serialized_start=180
  _globals['_PLUGINDATA']._serialized_end=206
  _globals['_PLUGINMARKETPLACE']._serialized_start=209
  _globals['_PLUGINMARKETPLACE']._serialized_end=339
# @@protoc_insertion_point(module_scope)
