[package]
name = "rust_bridge"
version = "0.1.0"
edition = "2021"

[dependencies]
tonic = { version = "0.11", features = ["transport"] }
tokio = { version = "1", features = ["rt-multi-thread", "macros"] }
prost = "0.12"

[build-dependencies]
tonic-build = "0.11"
