apiVersion: v1
kind: Service
metadata:
  name: {{ include "plugin-marketplace.fullname" . }}
  labels:
    app: {{ include "plugin-marketplace.name" . }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ include "plugin-marketplace.name" . }}
  ports:
    - port: {{ .Values.service.httpPort }}
      targetPort: {{ .Values.service.httpPort }}
      protocol: TCP
      name: http
    - port: {{ .Values.service.grpcPort }}
      targetPort: {{ .Values.service.grpcPort }}
      protocol: TCP
      name: grpc
