name: Claude Code Base Action

on:
  workflow_dispatch:

jobs:
  run-claude-code:
    runs-on: ubuntu-latest
    steps:
      - name: Claude Code Base Action
        uses: anthropics/claude-code-base-action@beta
        with:
          prompt: "Hello from Claude Code Base Action"
          allowed_tools: "Bash(git:*),View,GlobTool,GrepTool,BatchTool"
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
