name: Grafana Deploy

on:
  push:
    paths:
      - 'grafana/dashboards/**'

jobs:
  apply:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.lock
      - name: Apply dashboards
        env:
          GRAFANA_URL: ${{ secrets.GRAFANA_URL }}
          GRAFANA_API_KEY: ${{ secrets.GRAFANA_API_KEY }}
        run: python scripts/apply_dashboards.py
      - name: Notify Slack success
        if: success()
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: |
          curl -X POST -H 'Content-type: application/json' \
            --data '{"text":"Grafana workflow succeeded for ${{ github.repository }} at ${{ github.sha }}"}' \
            "$SLACK_WEBHOOK_URL"
      - name: Notify Slack failure
        if: failure()
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: |
          curl -X POST -H 'Content-type: application/json' \
            --data '{"text":"Grafana workflow failed for ${{ github.repository }} at ${{ github.sha }}"}' \
            "$SLACK_WEBHOOK_URL"
